name: homelist_monorepo

packages:
  - packages/*

scripts:
  build:
    run: dart pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1

  run:homelist:
    run: flutter run
    exec:
      scope: "homelist"
